# Generated by Django 5.0.2 on 2024-02-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0004_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='Contact',
        ),
    ]
